config/routes.rb
ActionController::Routing::Routes.draw do |map|

  map.resources   :locations
  map.resources   :groups
  
  map.root        :controller => "locations"
  
end

app/models/alert_sender.rb
# Checks if there are any alerts that we need to fire since last time.
class AlertSender
end

app/models/feed_updater.rb
# Updates feeds of all location calendars
class FeedUpdater
  
  # Updates all location feeds
  def update_all
    Location.with_feed.each { |l| update(l) }
  end
  
  # Updates location feed
  def update(location)
    puts "Updating: #{location.name} (#{location.keyword})"
    
    # Update location record
    location.vcalendar = read_vcalendar(location)
    location.feed_updated_at = Time.now
    location.save
  rescue => e
    # Report somewhere
  end

  private
  
  # Returns associated vcalendar feed text
  def read_vcalendar(location)
    uri = URI.parse(location.feed_url)
    res = Net::HTTP.get_response(uri)
    res.body
  end

end

app/models/group.rb
class Group < ActiveRecord::Base

  has_many :locations

  validates_presence_of :name

end

app/models/location.rb
class Location < ActiveRecord::Base

  belongs_to :group

  validates_presence_of   :name
  validates_presence_of   :keyword
  validates_uniqueness_of :keyword
  validates_format_of     :alert_offsets, :with => /^(\d+(,\d+)*)?$/, :message => "has invalid format. Comma-separated hours please (0,1,25)"

  before_create :init_checked_at
  
  # All locations with feed urls set
  named_scope :with_feed, :conditions => "feed_url IS NOT NULL"
  
  # Returns the array of integers
  def alert_offset_list
    self.alert_offsets.blank? ? [] : self.alert_offsets.split(/\s*,\s*/).map(&:to_i).uniq
  end

  def sponsor
    !group.nil? && group.sponsor
  end
  
  private
  
  # Initializes checked_at
  def init_checked_at
    self.checked_at = Time.now
  end
  
end

app/models/messenger.rb
class Messenger

  # Sends messages related to a given location to clients
  def self.send_messages(location, messages)
    return if messages.blank? || location.blank?
    
    keyword = location.keyword
    messages.each do |message|
      send_message(keyword, message)
    end
  end

  # Sends a subscription message for a given keyword
  def self.send_message(keyword, message)
    if RAILS_ENV == 'development' || RAILS_ENV == 'test'
      puts "Sending '#{message}' to '#{keyword}'"
    else
      url = SERVICE_LAYER_API_URL + "/send_subscription_message"
      data = {
        :api_key          => SERVICE_LAYER_API_KEY,
        :body             => message,
        :tags             => keyword
      }
    
      Net::HTTP.post_form(URI.parse(url), data)
    end
  end
  
end

app/models/schedule.rb
class Schedule

  MSG_LENGTH = 160
  
  attr_reader :timezone
  
  # Initializes the model with some calendar
  def initialize(location)
    @location = location
    if location.nil? || location.alert_offsets.blank?
      @calendar = nil
      @timezone = nil
    else
      @calendar = Schedule.init_calendar(location.vcalendar)
      @timezone = Schedule.get_timezone(@calendar)
    end
  end
  
  # Returns messages array to send for the time frame since the given #time#
  # to the present.
  def messages_to_send_since(start_time, end_time = Time.now)
    return [] if @calendar.nil?

    messages = []
    
    @location.alert_offset_list.each do |offset|
      events = events_in_range(start_time + offset.hours, end_time + offset.hours)
      unless events.empty?
        suffix    = Schedule.offset_to_suffix(offset)
        messages += events.map do |event|
          compose_message(event, suffix, @location.sponsor)
        end
      end
    end
    
    return messages
  end
  
  private
  
  # Initializes calendar from data
  def self.init_calendar(data)
    return nil if data.blank?
    calendars = Vpim::Icalendar.decode(data)
    calendars.first
  rescue => e
    # Log the error somewhere
    return nil
  end
  
  # Returns the timezone if present in the calendar feed
  def self.get_timezone(calendar)
    field = calendar.fields.find { |f| f.name == 'X-WR-TIMEZONE' }
    field.nil? ? nil : TZInfo::Timezone.get(field.value)
  rescue => e
    return nil
  end
  
  # Returns time in the feed timezone or time itself
  def self.with_timezone(time, timezone)
    timezone.nil? ? time : timezone.utc_to_local(time)
  end
  
  # Returns suffix with textual description of the offset
  def self.offset_to_suffix(offset)
    return "" if offset == 0

    now  = Time.now
    nxt  = now + offset.hours
    diff = (nxt.beginning_of_day - now.beginning_of_day) / 1.day.to_i
    
    if diff < 1
      return "today"
    elsif diff < 2
      return "tomorrow"
    else
      return "in #{diff.to_i} days"
    end
  end
  
  # Returns events with alerts in the given time frame
  def events_in_range(start_time, end_time)
    @calendar.components(Vpim::Icalendar::Vevent).select do |event|
      event_in_range(event, start_time, end_time)
    end
  end

  # Returns TRUE if an event is in range. All-day events are checked as starting at 8am.
  def event_in_range(event, start_time, end_time)
    occurs = event.occurs_in?(start_time, end_time)
    if occurs
      if event.duration == 1.day 
        mark = start_time.beginning_of_day + 8.hours
      else
        offs = event.dtstart - event.dtstart.beginning_of_day
        mark = start_time.beginning_of_day + offs
      end
      
      return start_time < mark && mark <= end_time
    else
      return occurs
    end
  end

  def compose_message(event, suffix, sponsor)
    text = event.description || event.summary
    
    unless suffix.blank?
      t = Schedule.with_timezone(event.dtstart, @timezone)
      suffix = " (#{suffix}, #{t.to_s(:message)})"
    end

    unless sponsor.blank?
      max_text_len = MSG_LENGTH - (sponsor.length + 1) - (suffix.to_s.length + 1)
      sponsor      = "\n#{sponsor}"
      text         = text[0, max_text_len]
    end
    
    [ text, suffix, sponsor ].reject(&:blank?).join
  end
end

app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details

  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password

  before_filter :authenticate

  private
  
  # Simple authentication that is called before any admin action
  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == ADMIN_USERNAME && password == ADMIN_PASSWORD
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < InheritedResources::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  rescue_from ActiveRecord::RecordNotFound, :with => :redirect_to_index
  
  # Shows the list of all locations
  def index
    @locations = Location.all
  end
  
  # Shows the location details
  def show
    @location = Location.find(params[:id])
  end
  
  # New location form
  def new
    @location = Location.new
  end
  
  # Creates new location
  def create
    @location = Location.new(params[:location])
    if @location.save
      flash[:notice] = "Location record was created"
      redirect_to locations_url
    else
      render "new"
    end
  end
  
  # Edit location form
  def edit
    @location = Location.find(params[:id])
  end
  
  # Updates location
  def update
    @location = Location.find(params[:id])
    
    # Reset timestamps and cached calendar in case of the feed URL change
    if params[:location][:feed_url] != @location.feed_url
      params[:location][:checked_at]      = Time.now
      params[:location][:feed_updated_at] = nil
      params[:location][:vcalendar]       = nil
    end
    
    if @location.update_attributes(params[:location])
      flash[:notice] = "Location record was updated"
      redirect_to location_url(@location)
    else
      render "edit"
    end
  end
  
  # Destroys location
  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to locations_url
  end

  private
  
  # Redirects to the locations list
  def redirect_to_index
    redirect_to locations_url
  end
end

app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/groups/_form.haml
= form.error_messages

.field
  = form.label      :name, "Group Name"
  = form.text_field :name

.field
  = form.label      :sponsor, "Sponsor message"
  = form.text_field :sponsor

.field
  = form.label      :locations
  %ul.locations
    - lids = form.object.location_ids
    - for l in Location.all
      %li
        = check_box_tag "group[location_ids][]", l.id, lids.include?(l.id)
        = h(l.name)

app/views/groups/edit.haml
%h1 Update Group

- form_for @group do |f|
  = render :partial => f
  .commit= f.submit "Update Group"

.commands
  = link_to "Back to Groups", collection_url

app/views/groups/index.haml
%h1 Groups

%table.groups
  %tr
    %th.name          Name
    %th.sponsor       Sponsor
    %th.locations     Locations
    %th.ops           Operations
  - for g in collection
    %tr
      %td.name=           link_to h(g.name), resource_path(g)
      %td.sponsor=        h(g.sponsor)
      %td.locations=      h(g.locations.count)
      %td.ops
        = link_to "Edit",   edit_resource_path(g)
        = link_to "Delete", resource_path(g), :confirm => "Are you sure?", :method => :delete

.commands
  = link_to "Add Group", new_resource_path

app/views/groups/new.haml
%h1 New Group

- form_for @group do |f|
  = render :partial => f
  .commit= f.submit "Add Group"

.commands
  = link_to "Back to Groups", collection_path

app/views/groups/show.haml
%h1 Group: #{h(@group.name)}

%table.properties
  %tr
    %td.label Name:
    %td=      h(@group.name)
  %tr
    %td.label Sponsor message:
    %td=      h(@group.sponsor)
  %tr
    %td.label Locations:
    %td
      - if @group.locations.empty?
        No locations assigned
      - else
        %ul
          - for l in @group.locations
            %li= link_to h(l.name), l

.commands
  = link_to "Back to Groups", collection_path
  = link_to "Edit",           edit_resource_path(@group)
  = link_to "Delete",         @group, :confirm => "Are you sure?", :method => :delete

app/views/layouts/_header.haml
#menu
  %ul
    %li= link_to "Groups", groups_path
    %li= link_to "Locations", locations_path

app/views/layouts/application.haml
!!!
%html{ "xmlns" => "http://www.w3.org/1999/xhtml", "xml:lang" => "en", "lang" => "en" }
  %head
    %meta{ "http-equiv" => "content-type", "content" => "text/html;charset=UTF-8" }
    %title AntiTow
    = javascript_include_tag 'prototype', 'effects', 'dragdrop', 'controls'
    = javascript_include_tag 'application'
    = stylesheet_link_tag 'reset', 'global'
    = javascript_tag "window._token = '#{form_authenticity_token}'" if ActionController::Base.allow_forgery_protection
  %body
    #page.wrapper
      = render :partial => "layouts/header"
      #content
        #mainarea= yield
      = render :partial => "layouts/footer"

app/views/locations/_form.haml
= form.error_messages

.field
  = form.label      :name, "Location Name"
  = form.text_field :name

.field
  = form.label      :keyword, "Associated Subscription Keyword"
  = form.text_field :keyword

.field
  = form.label      :feed_url, "iCal feed URL"
  = form.text_field :feed_url

.field
  = form.label      :alert_offsets, "Alert offsets (comma-separated hours)"
  = form.text_field :alert_offsets

.field
  = form.label      :description
  = form.text_area  :description, :rows => 5

app/views/locations/edit.haml
%h1 Update Location

- form_for @location do |f|
  = render :partial => f
  .commit= f.submit "Update Location"

.commands
  = link_to "Back to Locations", locations_url

app/views/locations/index.haml
%h1 Locations

%table.locations
  %tr
    %th.name          Name
    %th.keyword       Keyword
    %th.feed_url      Feed URL
    %th.alert_offsets Alert Offsets (hours)
    %th.ops           Operations
  - for l in @locations
    %tr
      %td.name=           link_to h(l.name), location_path(l)
      %td.keyword=        h(l.keyword)
      %td.feed_url=       h(l.feed_url)
      %td.alert_offsets=  h(l.alert_offsets)
      %td.ops
        = link_to "Edit", edit_location_path(l)
        = link_to "Delete", location_path(l), :confirm => "Are you sure?", :method => :delete

.commands
  = link_to "Add Location", new_location_path

    

app/views/locations/new.haml
%h1 New Location

- form_for @location do |f|
  = render :partial => f
  .commit= f.submit "Add Location"

.commands
  = link_to "Back to Locations", locations_url

app/views/locations/show.haml
%h1 Location: #{h(@location.name)}

%table.properties
  %tr
    %td.label Name:
    %td=      h(@location.name)
  %tr
    %td.label Keyword:
    %td=      h(@location.keyword)
  %tr
    %td.label Description:
    %td=      h(@location.description)
  %tr
    %td.label iCal feed URL:
    %td=      h(@location.feed_url)
  %tr
    %td.label Alert Offsets (hours):
    %td=      h(@location.alert_offsets)
  %tr
    %td.label Last checked at:
    %td=      h(@location.checked_at.to_s(:details))
  %tr
    %td.label Last updated at:
    %td=      @location.feed_updated_at && h(@location.feed_updated_at.to_s(:details))

.commands
  = link_to "Back to Locations", locations_path
  = link_to "Edit", edit_location_path(@location)
  = link_to "Delete", location_path(@location), :confirm => "Are you sure?", :method => :delete